name: build

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["client", "services/api", "pulumi"]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["services/api", "pulumi"]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["services/api"]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose up -d
      - run: npm ci
      - run: npm run test:e2e

  build-api:
    needs: [lint, test, e2e-test]
    if: github.ref == 'refs/heads/develop'
    uses: jbrunton/workflows/.github/workflows/build-image.yml@develop
    with:
      repo-name: jbrunton/auth0-test-api
      working-directory: services/api
      buildpack: paketo-buildpacks/nodejs
      publish: true
      docker-username: jbrunton
      cache-image: jbrunton/auth0-test-api-cache-image:latest
    secrets:
      docker-access-token: ${{ secrets.DOCKER_ACCESS_TOKEN }}

  deploy-staging:
    environment:
      name: Staging
      url: https://auth0-test.staging.jbrunton-aws.com
    concurrency: staging
    needs: [build-api]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Client
        env:
            VITE_API_URL: https://auth0-test-api.staging.jbrunton-aws.com
        run: |
          npm ci
          npm run build
        working-directory: client
      - run: npm ci
        working-directory: pulumi
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: staging
          upsert: true
          work-dir: pulumi
          comment-on-pr: true
          github-token: ${{ secrets.CI_MINION_PAT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          TAG: ${{ needs.build-api.outputs.tag }}

  deploy-production:
    environment:
      name: Production
      url: https://auth0-test.jbrunton-aws.com
    concurrency: production
    needs: [build-api, deploy-staging]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        env:
          VITE_API_URL: https://auth0-test-api.jbrunton-aws.com
        run: |
          npm ci
          npm run build
        working-directory: client
      - run: npm ci
        working-directory: pulumi
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          upsert: true
          work-dir: pulumi
          comment-on-pr: true
          github-token: ${{ secrets.CI_MINION_PAT }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          TAG: ${{ needs.build-api.outputs.tag }}
